BULK INSERT BRONZE.RETAIL_SALES_DETAILS
FROM "C:\Users\vishw\OneDrive\Desktop\projects\EYproject\retail_data.csv"
WITH(
FIRSTROW=2,
FORMAT='CSV',
FIELDTERMINATOR=',',
ROWTERMINATOR='\n',
CODEPAGE = '65001', 
TABLOCK
);
SELECT * FROM BRONZE.RETAIL_SALES_DETAILS;