USE RETAIL_DATA_WAREHOUSE;

DROP TABLE GOLD.DIM_CUSTOMER
CREATE TABLE GOLD.DIM_CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME NVARCHAR(50),
CUSTOMER_EMAIL NVARCHAR(50),
CUSTOMER_PHONE NVARCHAR(15),
CUSTOMER_ADDRESS NVARCHAR(100),
CUSTOMER_CITY NVARCHAR(50),
CUSTOMER_STATE NVARCHAR(50),
CUSTOMER_ZIPCODE INT,
CUSTOMER_COUNTRY NVARCHAR(50),
CUSTOMER_AGE INT,
CUSTOMER_GENDER NVARCHAR(7),
CUSTOMER_INCOME NVARCHAR(50),
CUSTOMER_SEGMENT NVARCHAR(20)
)

CREATE TABLE GOLD.DIM_PRODUCT(
 PRODUCT_ID INT PRIMARY KEY,
  PRODUCT_CAT NVARCHAR(30),
  PRODUCT_BRAND NVARCHAR(30),
  PRODUCT_TYPE NVARCHAR(50),
  PRODUCT_FEEDBACK NVARCHAR(50),
  PRODUCT_SHIPPING NVARCHAR(50),
  PRODUCTS NVARCHAR(50)
);

DROP TABLE GOLD.FACT_SALES;
CREATE TABLE GOLD.FACT_SALES(

 FACT_ID INT IDENTITY(1,1) PRIMARY KEY,
 TRANSACTION_ID INT,
 CUSTOMER_ID INT FOREIGN KEY REFERENCES GOLD.DIM_CUSTOMER(CUSTOMER_ID),
 PRODUCT_ID INT FOREIGN KEY REFERENCES GOLD.DIM_PRODUCT(PRODUCT_ID),
 TRANSACTION_DATE DATE,
 TRANSACTION_TIME TIME,
 CUSTOMER_PURCHASES INT,
 TRANSACTION_AMOUNT FLOAT,
 TOTAL_AMOUNT FLOAT,
 PRODUCT_RATING INT,
)

CREATE TABLE GOLD.FACT_SALES_EXTENDED (
    FACT_ID INT IDENTITY(1,1) PRIMARY KEY,

    
    TRANSACTION_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,

    
    CUSTOMER_NAME NVARCHAR(50),
    CUSTOMER_EMAIL NVARCHAR(50),
    CUSTOMER_PHONE NVARCHAR(15),
    CUSTOMER_CITY NVARCHAR(50),
    CUSTOMER_STATE NVARCHAR(50),
    CUSTOMER_COUNTRY NVARCHAR(50),
    CUSTOMER_AGE INT,
    CUSTOMER_GNDR NVARCHAR(7),
    CUSTOMER_SEGMENT NVARCHAR(20),

    
    PRODUCT_CAT NVARCHAR(30),
    PRODUCT_BRAND NVARCHAR(30),
    PRODUCT_TYPE NVARCHAR(50),
    PRODUCT_FEEDBACK NVARCHAR(50),
    PRODUCT_SHIPPING NVARCHAR(50),
    PRODUCTS NVARCHAR(50),

    
    TRANSACTION_DATE DATE,
    TRANSACTION_TIME TIME,
    CUSTOMER_PURCHASES INT,
    TRANSACTION_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    PRODUCT_RATING INT,
    TRANSACTION_METHOD NVARCHAR(30),
    ORDER_STATUS NVARCHAR(30)
);
