USE RETAIL_DATA_WAREHOUSE;
INSERT INTO GOLD.DIM_CUSTOMER(
CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, CUSTOMER_ADDRESS,
  CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIPCODE, CUSTOMER_COUNTRY,
  CUSTOMER_AGE, CUSTOMER_GNDR, CUSTOMER_INCOME, CUSTOMER_SEGMENT
)
SELECT DISTINCT
  CUST_ID, CUST_NAME, CUST_EMAIL, CUST_PHONE, CUST_ADDRESS,
  CUST_CITY, CUST_STATE, CUST_ZIPCODE, CUST_COUNTRY,
  CUST_AGE, CUST_GNDR, CUST_INCOME, CUST_SEGMENT
FROM SILVER.RETAIL_SALES_DETAILS;

INSERT INTO GOLD.DIM_PRODUCT(
PRODUCT_ID, PRODUCT_CAT, PRODUCT_BRAND, PRODUCT_TYPE,
  PRODUCT_FEEDBACK, PRODUCT_SHIPPING, PRODUCTS

)
SELECT 
ROW_NUMBER() OVER (ORDER BY PRODUCT_CAT, PRODUCT_BRAND, PRODUCT_TYPE) AS PRODUCT_ID,
 PRODUCT_CAT,
  PRODUCT_BRAND,
  PRODUCT_TYPE,
  PRODUCT_FEEDBACK,
  PRODUCT_SHIPPING,
  PRODUCTS
FROM SILVER.RETAIL_SALES_DETAILS


INSERT INTO GOLD.FACT_SALES(
TRANSACTION_ID,
  CUSTOMER_ID,
  PRODUCT_ID,
  TRANSACTION_DATE,
  TRANSACTION_TIME,
  CUSTOMER_PURCHASES,
  TRANSACTION_AMOUNT,
  TOTAL_AMOUNT,
  PRODUCT_RATING
)
SELECT
 S.TRANSACTION_ID,
 C.CUSTOMER_ID,
 P.PRODUCT_ID,
 S.TRANSACTION_DATE,
 S.TRANSACTION_TIME,
 S.CUST_PURCHASES AS CUSTOMER_PURCHASES,
 S.TRANSACTION_AMOUNT,
 S.TOTAL_AMOUNT,
 S.PRODUCT_RATING
 FROM SILVER.RETAIL_SALES_DETAILS S
 JOIN GOLD.DIM_CUSTOMER C
 ON S.CUST_ID=C.CUSTOMER_ID
 JOIN GOLD.DIM_PRODUCT P
  ON S.PRODUCT_CAT = P.PRODUCT_CAT
 AND S.PRODUCT_BRAND = P.PRODUCT_BRAND
 AND S.PRODUCT_TYPE = P.PRODUCT_TYPE
 AND S.PRODUCT_FEEDBACK = P.PRODUCT_FEEDBACK
 AND S.PRODUCT_SHIPPING = P.PRODUCT_SHIPPING
 AND S.PRODUCTS = P.PRODUCTS;




