import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('../retail_data.csv')
print("The shape of dataset is",data.shape)
print("\n")
print("The datatypes available are\n")
print(data.dtypes)
print("\n")
print("The first five rows\n")
print(data.head())
print("\n")
print("The last five rows\n")
print(data.tail())
print("\n")
print("Here is information about the dataset\n")
print(data.info())
print("\n")
print("Here is a description of a dataset\n")
print(data.describe())
print("\n")

print("Here are the total null values\n")
print(data.isnull().sum())
print("\n")
print("Here are the total duplicated values\n")
print(data.duplicated().sum())
print("\n")
print(data[data.duplicated()])
print("\n")
print("Here are the unique values\n")
print(data.nunique())
print("\n")
print("Here is the correlation\n")
print(data.corr(numeric_only=True))
plt.figure(figsize=(8,6))
sns.heatmap(data.corr(numeric_only=True),cmap='coolwarm')
plt.show()
print("Here is the covariance matrix\n")
print(data.cov(numeric_only=True))
print("\n")
