USE RETAIL_DATA_WAREHOUSE;
DROP TABLE IF EXISTS SILVER.RETAIL_SALES_DETAILS;

CREATE TABLE SILVER.RETAIL_SALES_DETAILS (
 TRANSACTION_ID INT,
 CUST_ID INT,
 CUST_NAME NVARCHAR(50),
 CUST_EMAIL NVARCHAR(50),
 CUST_PHONE NVARCHAR(15),
 CUST_ADDRESS NVARCHAR(100),
 CUST_CITY NVARCHAR(50),
 CUST_STATE NVARCHAR(50),
 CUST_ZIPCODE INT,
 CUST_COUNTRY NVARCHAR(50),
 CUST_AGE INT,
 CUST_GNDR NVARCHAR(7),
 CUST_INCOME NVARCHAR(50),
 CUST_SEGMENT NVARCHAR(20),
 TRANSACTION_DATE DATE,  
 TRANSACTION_TIME TIME,
 CUST_PURCHASES INT,
 TRANSACTION_AMOUNT FLOAT,
 TOTAL_AMOUNT FLOAT,
 PRODUCT_CAT NVARCHAR(30),
 PRODUCT_BRAND NVARCHAR(30),
 PRODUCT_TYPE NVARCHAR(50),
 PRODUCT_FEEDBACK NVARCHAR(50),
 PRODUCT_SHIPPING NVARCHAR(50),
 TRANSACTION_METHOD NVARCHAR(30),
 ORDER_STATUS NVARCHAR(30),
 PRODUCT_RATING INT,
 PRODUCTS NVARCHAR(50) 
);

