USE RETAIL_DATA_WAREHOUSE;
TRUNCATE TABLE SILVER.RETAIL_SALES_DETAILS;




WITH LatestPerTransaction AS (
  SELECT *, 
         ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY TRANSACTION_DATE DESC) AS RN_Trans
  FROM BRONZE.RETAIL_SALES_DETAILS
),
FilteredTransaction AS (
  SELECT * FROM LatestPerTransaction WHERE RN_Trans = 1
),
LatestPerCustomer AS (
  SELECT *, 
         ROW_NUMBER() OVER (PARTITION BY CUST_ID ORDER BY TRANSACTION_DATE DESC) AS RN_Cust
  FROM FilteredTransaction
),
FilteredCustomer AS (
  SELECT * FROM LatestPerCustomer WHERE RN_Cust = 1
)
INSERT INTO SILVER.RETAIL_SALES_DETAILS
SELECT 
  CASE 
    WHEN TRANSACTION_ID IS NULL THEN 
      CASE 
        WHEN CUST_ID IS NOT NULL THEN CUST_ID 
        ELSE CONCAT('TXN_', ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) 
      END 
    ELSE TRANSACTION_ID 
  END AS TRANSACTION_ID,

  CASE 
    WHEN CUST_ID IS NULL THEN 
      CASE 
        WHEN TRANSACTION_ID IS NOT NULL THEN TRANSACTION_ID 
        ELSE CONCAT('CUST_', ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) 
      END 
    ELSE CUST_ID 
  END AS CUST_ID,

  CASE WHEN CUST_NAME IS NULL THEN 'N/A' ELSE CUST_NAME END AS CUST_NAME,
  CASE WHEN CUST_EMAIL IS NULL THEN 'N/A' ELSE CUST_EMAIL END AS CUST_EMAIL,
  CASE WHEN CUST_PHONE IS NULL THEN 'N/A' ELSE CUST_PHONE END AS CUST_PHONE,
  CASE WHEN CUST_ADDRESS IS NULL THEN 'N/A' ELSE CUST_ADDRESS END AS CUST_ADDRESS,
  CASE WHEN CUST_CITY IS NULL THEN 'N/A' ELSE CUST_CITY END AS CUST_CITY,
  CASE WHEN CUST_STATE IS NULL THEN 'N/A' ELSE CUST_STATE END AS CUST_STATE,
  CASE WHEN CUST_ZIPCODE IS NULL THEN 0 ELSE CUST_ZIPCODE END AS CUST_ZIPCODE,
  CASE WHEN CUST_COUNTRY IS NULL THEN 'N/A' ELSE CUST_COUNTRY END AS CUST_COUNTRY,
  CASE WHEN CUST_AGE IS NULL THEN 0 ELSE CUST_AGE END AS CUST_AGE,
  CASE WHEN CUST_GNDR IS NULL THEN 'N/A' ELSE CUST_GNDR END AS CUST_GNDR,
  CASE WHEN CUST_INCOME IS NULL THEN 'N/A' ELSE CUST_INCOME END AS CUST_INCOME,
  CASE WHEN CUST_SEGMENT IS NULL THEN 'N/A' ELSE CUST_SEGMENT END AS CUST_SEGMENT,


   CASE 
  WHEN TRANSACTION_DATE IS NOT NULL THEN TRANSACTION_DATE
  WHEN TRANSACTION_YEAR IS NOT NULL AND TRANSACTION_MONTH IS NOT NULL THEN 
    TRY_CAST(
      CONCAT(
        TRANSACTION_YEAR, '-', 
        CASE 
          WHEN TRANSACTION_MONTH = 'January' THEN '01'
          WHEN TRANSACTION_MONTH = 'February' THEN '02'
          WHEN TRANSACTION_MONTH = 'March' THEN '03'
          WHEN TRANSACTION_MONTH = 'April' THEN '04'
          WHEN TRANSACTION_MONTH = 'May' THEN '05'
          WHEN TRANSACTION_MONTH = 'June' THEN '06'
          WHEN TRANSACTION_MONTH = 'July' THEN '07'
          WHEN TRANSACTION_MONTH = 'August' THEN '08'
          WHEN TRANSACTION_MONTH = 'September' THEN '09'
          WHEN TRANSACTION_MONTH = 'October' THEN '10'
          WHEN TRANSACTION_MONTH = 'November' THEN '11'
          WHEN TRANSACTION_MONTH = 'December' THEN '12'
          ELSE NULL
        END,
        '-01'
      ) AS DATE
    )
  ELSE NULL
END AS TRANSACTION_DATE

  ,
  CASE 
  WHEN TRANSACTION_TIME IS NULL THEN CAST('00:00:00' AS TIME(0))
  ELSE CAST(TRANSACTION_TIME AS TIME(0))
END AS TRANSACTION_TIME

  ,
  CASE WHEN CUST_PURCHASES IS NULL THEN 0 ELSE CUST_PURCHASES END AS CUST_PURCHASES,
  CASE WHEN TRANSACTION_AMOUNT IS NULL THEN 0 ELSE ROUND(TRANSACTION_AMOUNT,2) END AS TRANSACTION_AMOUNT,
  CASE WHEN TOTAL_AMOUNT IS NULL THEN 0 ELSE ROUND(TOTAL_AMOUNT,2) END AS TOTAL_AMOUNT,
  ISNULL(PRODUCT_CAT, 'N/A') AS PRODUCT_CAT,
  ISNULL(PRODUCT_BRAND, 'N/A') AS PRODUCT_BRAND,
  ISNULL(PRODUCT_TYPE, 'N/A') AS PRODUCT_TYPE,
  ISNULL(PRODUCT_FEEDBACK, 'N/A') AS PRODUCT_FEEDBACK,
  ISNULL(PRODUCT_SHIPPING, 'N/A') AS PRODUCT_SHIPPING,
  ISNULL(TRANSACTION_METHOD, 'N/A') AS TRANSACTION_METHOD,
  ISNULL(ORDER_STATUS, 'N/A') AS ORDER_STATUS,
  ISNULL(PRODUCT_RATING, 0) AS PRODUCT_RATING,
  ISNULL(PRODUCTS, 'N/A') AS PRODUCTS
FROM FilteredCustomer;
