USE RETAIL_DATA_WAREHOUSE;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS;
SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE TRANSACTION_ID IS NULL;

SELECT TRANSACTION_ID,COUNT(*) FROM SILVER.RETAIL_SALES_DETAILS GROUP BY TRANSACTION_ID HAVING COUNT(*)>1;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE CUST_ID IS NULL;


SELECT TRANSACTION_ID,COUNT(*) FROM SILVER.RETAIL_SALES_DETAILS GROUP BY TRANSACTION_ID HAVING COUNT(*)>1;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE CUST_NAME IS NULL;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE CUST_EMAIL IS NULL;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE CUST_PHONE IS NULL;

SELECT * FROM SILVER.RETAIL_SALES_DETAILS WHERE TRANSACTION_DATE IS NULL;

SELECT TRANSACTION_ID,TRANSACTION_DATE,TRANSACTION_MONTH,TRANSACTION_YEAR FROM BRONZE.RETAIL_SALES_DETAILS WHERE TRANSACTION_DATE IS NULL;

SELECT TRANSACTION_TIME FROM SILVER.RETAIL_SALES_DETAILS WHERE TRANSACTION_TIME IS NULL

SELECT COUNT(*) FROM BRONZE.RETAIL_SALES_DETAILS WHERE TRANSACTION_DATE IS NULL


SELECT COUNT(*) FROM SILVER.RETAIL_SALES_DETAILS WHERE TRANSACTION_DATE IS NULL

SELECT DISTINCT PRODUCT_RATING FROM SILVER.RETAIL_SALES_DETAILS;
SELECT DISTINCT TRANSACTION_TIME FROM SILVER.RETAIL_SALES_DETAILS;
