
SELECT 'Total sales' AS measure_name,SUM(TOTAL_AMOUNT) AS measure_value FROM GOLD.FACT_SALES_EXTENDED 
UNION ALL
SELECT 'Average sale', AVG(TOTAL_AMOUNT) FROM GOLD.FACT_SALES_EXTENDED 
UNION ALL
SELECT 'Total purchases', SUM(CUSTOMER_PURCHASES)  FROM GOLD.FACT_SALES_EXTENDED
UNION ALL
SELECT 'Total categories', COUNT( DISTINCT PRODUCT_CAT)  FROM GOLD.FACT_SALES_EXTENDED
UNION ALL
SELECT'Total cities', COUNT(DISTINCT CUSTOMER_CITY) FROM GOLD.FACT_SALES_EXTENDED
UNION ALL
SELECT 'Total brands' ,COUNT(DISTINCT PRODUCT_BRAND) FROM GOLD.FACT_SALES_EXTENDED
UNION ALL
SELECT 'Total customers' ,COUNT(DISTINCT CUSTOMER_NAME) FROM GOLD.FACT_SALES_EXTENDED;


