USE RETAIL_DATA_WAREHOUSE;

SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DIM_CUSTOMER';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DIM_PRODUCT';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='FACT_SALES_EXTENDED';