SELECT TRANSACTION_DATE FROM GOLD.FACT_SALES_EXTENDED;

SELECT MIN(TRANSACTION_DATE) AS FIRST_ORDER_DATE,MAX(TRANSACTION_DATE) AS LAST_ORDER_DATE FROM GOLD.FACT_SALES_EXTENDED;

SELECT DATEDIFF(year,MIN(TRANSACTION_DATE),MAX(TRANSACTION_DATE)) AS NO_OF_YEARS FROM GOLD.FACT_SALES_EXTENDED;


SELECT CUSTOMER_NAME,CUSTOMER_AGE FROM GOLD.FACT_SALES_EXTENDED WHERE CUSTOMER_AGE=(
SELECT MIN(CUSTOMER_AGE) FROM GOLD.FACT_SALES_EXTENDED WHERE CUSTOMER_AGE!= 0);

SELECT CUSTOMER_NAME,CUSTOMER_AGE FROM GOLD.FACT_SALES_EXTENDED WHERE CUSTOMER_AGE=( SELECT MAX(CUSTOMER_AGE) FROM GOLD.FACT_SALES_EXTENDED);

