	SELECT DISTINCT CUSTOMER_COUNTRY FROM GOLD.DIM_CUSTOMER;


	SELECT DISTINCT PRODUCT_CAT FROM GOLD.DIM_PRODUCT;




	SELECT DISTINCT CUSTOMER_COUNTRY,CUSTOMER_STATE,CUSTOMER_CITY FROM GOLD.DIM_CUSTOMER;


	SELECT PRODUCT_CAT,PRODUCT_BRAND,PRODUCTS FROM GOLD.DIM_PRODUCT ORDER BY 1,2,3;
