SELECT CUSTOMER_COUNTRY,COUNT(CUSTOMER_ID) AS NO_OF_CUSTOMERS FROM GOLD.FACT_SALES_EXTENDED GROUP BY CUSTOMER_COUNTRY ORDER BY NO_OF_CUSTOMERS DESC;

SELECT CUSTOMER_GNDR,COUNT(CUSTOMER_ID) AS NO_OF_CUSTOMERS FROM GOLD.FACT_SALES_EXTENDED GROUP BY CUSTOMER_GNDR ORDER BY NO_OF_CUSTOMERS DESC;

SELECT PRODUCT_CAT,COUNT(PRODUCT_ID) AS NO_OF_PRODUCTS FROM GOLD.FACT_SALES_EXTENDED GROUP BY PRODUCT_CAT ORDER BY COUNT(PRODUCT_CAT);

SELECT 
sum(F.TRANSACTION_AMOUNT) AS REVENUE,
P.PRODUCT_CAT
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_CAT;

SELECT P.PRODUCT_CAT,AVG(F.TRANSACTION_AMOUNT) AS AVERAGE_REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_CAT


SELECT 
sum(F.TRANSACTION_AMOUNT) AS REVENUE,
C.CUSTOMER_COUNTRY
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_CUSTOMER C
ON F.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.CUSTOMER_COUNTRY




