USE RETAIL_DATA_WAREHOUSE;

SELECT 
P.PRODUCTS,
SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCTS
ORDER BY REVENUE DESC;

SELECT 
P.PRODUCTS,
SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCTS
ORDER BY REVENUE;


SELECT TOP 5
P.PRODUCTS,
SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCTS
ORDER BY REVENUE DESC;


SELECT TOP 5
P.PRODUCTS,
SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCTS
ORDER BY REVENUE;


SELECT 
P.PRODUCTS,
SUM(F.TOTAL_AMOUNT) AS REVENUE,
ROW_NUMBER() OVER (ORDER BY SUM(F.TOTAL_AMOUNT) DESC ) AS RANK
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCTS
ORDER BY REVENUE DESC;


SELECT TOP 5
C.CUSTOMER_ID,
SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM GOLD.FACT_SALES_EXTENDED F
JOIN GOLD.DIM_CUSTOMER C
ON F.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY REVENUE DESC
